
platform :ios, '11.0'
use_frameworks!

target 'MoviesTv' do
    pod 'AFNetworking'
    pod 'RBStoryboardLink'
    pod 'ORStackView'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SwiftHTTP'
    pod 'JSONJoy-Swift'
    pod 'SVProgressHUD'
    pod 'Reusable'
    pod 'SwiftGen'
    pod 'DeviceKit'
    pod 'Kingfisher'
    
end

